title: Benchmark Project
email: 
description: >- # this means to ignore newlines until "baseurl:"
Benchmark project for computational inverse problems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# Build settings
theme: jekyll-theme-dinky
plugins:
  - jekyll-feed
